const obj = {
    TFT7_Sett: 1,
    TFT7_Tristana: 2,
    TFT7_Diana: 2,
    TFT7_Sejuani: 3,
    TFT7_Yone: 1,
    TFT7_Lillia: 1,
    TFT7_Nunu: 1,
    TFT7_Hecarim: 3,
    TFT7_DragonBlue: 1,
    TFT7_Yasuo: 4,
    TFT7_Bard: 7,
    TFT7_TahmKench: 1,
    TFT7_Jinx: 1,
    TFT7_Lulu: 4,
    TFT7_Corki: 1,
    TFT7_DragonPurple: 1,
    TFT7_Sona: 1,
    TFT7_TrainerDragon: 3,
    TFT7_Nidalee: 1,
    TFT7_Taric: 3,
    TFT7_Gnar: 3,
    TFT7_Thresh: 1,
    TFT7_Elise: 1,
    TFT7_Swain: 1,
    TFT7_Neeko: 3,
    TFT7_Shyvana: 1,
    TFT7_Karma: 3,
    TFT7_Ezreal: 3,
    TFT7_Leona: 2,
    TFT7_Ashe: 2,
    TFT7_LeeSin: 3,
    TFT7_Pyke: 2,
    TFT7_Soraka: 1,
    TFT7_Aatrox: 1,
    TFT7_Kayn: 2,
    TFT7_Qiyana: 4,
    TFT7_Talon: 5,
    TFT7_Ornn: 7,
    TFT7_DragonGold: 2,
    TFT7_Shen: 2,
    TFT7_Twitch: 4,
    TFT7_Xayah: 2,
    TFT7_Nami: 3,
    TFT7_Ryze: 1,
    TFT7_Varus: 2,
    TFT7_Illaoi: 2,
    TFT7_DragonGreen: 2,
    TFT7_Heimerdinger: 2,
    TFT7_Sylas: 2,
    TFT7_Zoe: 2,
    TFT7_AoShin: 2,
    TFT7_Anivia: 1
  };



  const a = "TFT7_Orn"

  console.log(a.split("_").pop());